-- 10. Create a sequence used when inserting records into the tables (point 11)

CREATE SEQUENCE SEQ_ADRESE START WITH 1;
CREATE SEQUENCE SEQ_CLIENTI START WITH 1;
CREATE SEQUENCE SEQ_COMENZI START WITH 1;
CREATE SEQUENCE SEQ_FEEDBACKURI START WITH 1;
CREATE SEQUENCE SEQ_PRODUSE START WITH 1;
CREATE SEQUENCE SEQ_COLECTII START WITH 1;
CREATE SEQUENCE SEQ_SARCINI START WITH 1;
CREATE SEQUENCE SEQ_ANGAJATI START WITH 1;
CREATE SEQUENCE SEQ_CROITORI START WITH 1;
CREATE SEQUENCE SEQ_DESIGNERI START WITH 1;
CREATE SEQUENCE SEQ_TIPARE START WITH 1;
CREATE SEQUENCE SEQ_MATERIALE START WITH 1;
CREATE SEQUENCE SEQ_CONTRACTE START WITH 1;
CREATE SEQUENCE SEQ_FURNIZORI START WITH 1;


-- 11. Creating tables in SQL and inserting coherent data in each of them (minimum 5
-- records in each non-associative table; minimum 10 records in the associative tables,
-- maximum 30 records in each table).

-- 1) Table CLIENTI

CREATE TABLE CLIENTI (
    ID_CLIENT NUMBER PRIMARY KEY,
    NUME VARCHAR2(30),
    PRENUME VARCHAR2(30),
    EMAIL VARCHAR2(40),
    NR_TEL VARCHAR2(15)
);

INSERT INTO CLIENTI (ID_CLIENT, NUME, PRENUME, EMAIL, NR_TEL)
VALUES (SEQ_CLIENTI.NEXTVAL, 'Stoivici', 'Alexandra', 'stoivici.alexandra@gmail.com', '+40711234567');

INSERT INTO CLIENTI
VALUES (SEQ_CLIENTI.NEXTVAL, 'Ionescu', 'Lidia', 'ionescu.lidia@gmail.com', '+40730097890');

INSERT INTO CLIENTI
VALUES (SEQ_CLIENTI.NEXTVAL, 'Popescu', 'Florin', 'popescu.florin@gmail.com', '+40799221443');

INSERT INTO CLIENTI
VALUES (SEQ_CLIENTI.NEXTVAL, 'Vasile', 'Cristian', 'vasile.cristian@gmail.com', '+40765222437');

INSERT INTO CLIENTI
VALUES (SEQ_CLIENTI.NEXTVAL, 'Marin', 'Mihaela', 'marin.mihaela@gmail.com', '+40766908123');

INSERT INTO CLIENTI
VALUES (SEQ_CLIENTI.NEXTVAL, 'Rusu', 'Ana-Maria', 'rusu.anamaria@gmail.com', '+40711654890');

INSERT INTO CLIENTI
VALUES (SEQ_CLIENTI.NEXTVAL, 'Vacaru', 'Marta', 'vacaru.marta@gmail.com', '+40760676248');

INSERT INTO CLIENTI
VALUES (SEQ_CLIENTI.NEXTVAL, 'Nicolae', 'Vladimir', 'nicolae.vladimir@gmail.com', '+40780091421');

SELECT *
FROM CLIENTI;


-- 2) Table ADRESE

CREATE TABLE ADRESE (
    ID_ADRESA NUMBER PRIMARY KEY,
    TARA VARCHAR2(40),
    JUDET VARCHAR2(40),
    ORAS VARCHAR2(40),
    STRADA VARCHAR2(40),
    NUMAR NUMBER CHECK (NUMAR > 0),
    SCARA NUMBER,
    APARTAMENT NUMBER,
    ID_CLIENT NUMBER,
    CONSTRAINT FK_ADRESE_CLIENTI FOREIGN KEY (ID_CLIENT) REFERENCES CLIENTI(ID_CLIENT)
);


INSERT INTO ADRESE (ID_ADRESA, TARA, JUDET, ORAS, STRADA, NUMAR, SCARA, APARTAMENT, id_client)
VALUES (SEQ_ADRESE.NEXTVAL, 'Romania', 'Bucuresti', 'Sector 4', 'Strada Micleni', 123, NULL, NULL, 1);

INSERT INTO ADRESE
VALUES (SEQ_ADRESE.NEXTVAL, 'Romania', 'Calarasi', 'Pucioasa', 'Strada Uverturii', 22, NULL, NULL, 2);

INSERT INTO ADRESE
VALUES (SEQ_ADRESE.NEXTVAL, 'Romania', 'Ilfov', 'Bragadiru', 'Strada Merilor', 26, 3, 21, 2);

INSERT INTO ADRESE
VALUES (SEQ_ADRESE.NEXTVAL, 'Romania', 'Sibiu', 'Sibiu', 'Strada Olfac', 3, 1, 2, 6);

INSERT INTO ADRESE
VALUES (SEQ_ADRESE.NEXTVAL, 'Romania', 'Alba', 'Alba Iulia', 'Calea Voiaj', 41, NULL, NULL, 4);

INSERT INTO ADRESE
VALUES (SEQ_ADRESE.NEXTVAL, 'Bulgaria', 'Vidin', 'Vidin', 'Straevskol', 6, NULL, NULL, 7);

INSERT INTO ADRESE
VALUES (SEQ_ADRESE.NEXTVAL, 'United Kingdom', 'Wales', 'Swansea', 'Kindom', 4, 2, 4, 5);

SELECT *
FROM ADRESE;


-- 3) Table COMENZI

CREATE TABLE COMENZI (
    ID_COMANDA NUMBER PRIMARY KEY,
    PRET DECIMAL(10, 2),
    LIVRARE VARCHAR2(10) CHECK (UPPER(LIVRARE) IN ('CURIER', 'POSTA', 'PERSONAL')),
    STARE VARCHAR2(10) CHECK (UPPER(STARE) IN ('PRELUATA', 'IN LUCRU', 'FINALIZATA', 'LIVRATA')),
    ID_CLIENT NUMBER NOT NULL,
    CONSTRAINT FK_COMENZI_CLIENTI FOREIGN KEY (ID_CLIENT) REFERENCES CLIENTI(ID_CLIENT)
);


INSERT INTO COMENZI (ID_COMANDA, LIVRARE, STARE, ID_CLIENT)
VALUES (SEQ_COMENZI.NEXTVAL, 'CURIER', 'PRELUATA', 1);

INSERT INTO COMENZI (ID_COMANDA, LIVRARE, STARE, ID_CLIENT)
VALUES (SEQ_COMENZI.NEXTVAL, 'PERSONAL', 'IN LUCRU', 3);

INSERT INTO COMENZI (ID_COMANDA, LIVRARE, STARE, ID_CLIENT)
VALUES (SEQ_COMENZI.NEXTVAL, 'POSTA', 'LIVRATA', 4);

INSERT INTO COMENZI (ID_COMANDA, LIVRARE, STARE, ID_CLIENT)
VALUES (SEQ_COMENZI.NEXTVAL, 'CURIER', 'FINALIZATA', 2);

INSERT INTO COMENZI (ID_COMANDA, LIVRARE, STARE, ID_CLIENT)
VALUES (SEQ_COMENZI.NEXTVAL, 'POSTA', 'PRELUATA', 1);

INSERT INTO COMENZI (ID_COMANDA, LIVRARE, STARE, ID_CLIENT)
VALUES (SEQ_COMENZI.NEXTVAL, 'CURIER', 'IN LUCRU', 7);

INSERT INTO COMENZI (ID_COMANDA, LIVRARE, STARE, ID_CLIENT)
VALUES (SEQ_COMENZI.NEXTVAL, 'PERSONAL', 'FINALIZATA', 6);

INSERT INTO COMENZI (ID_COMANDA, LIVRARE, STARE, ID_CLIENT)
VALUES (SEQ_COMENZI.NEXTVAL, 'CURIER', 'PRELUATA', 7);

SELECT *
FROM COMENZI;


-- 4) Table FEEDBACKURI

CREATE TABLE FEEDBACKURI (
    ID_FEEDBACK NUMBER PRIMARY KEY,
    NOTA NUMBER CHECK (NOTA > 0 AND NOTA <= 10),
    DESCRIERE VARCHAR2(500),
    ID_COMANDA NUMBER NOT NULL,
    CONSTRAINT FK_FEEDBACKURI_COMENZI FOREIGN KEY (ID_COMANDA) REFERENCES COMENZI(ID_COMANDA)
);


INSERT INTO FEEDBACKURI (id_feedback, nota, descriere, id_comanda)
VALUES (SEQ_FEEDBACKURI.NEXTVAL, 10, 'Prompt si calitativ', 3);

INSERT INTO FEEDBACKURI
VALUES (SEQ_FEEDBACKURI.NEXTVAL, 8, NULL, 2);

INSERT INTO FEEDBACKURI
VALUES (SEQ_FEEDBACKURI.NEXTVAL, 9, 'Calitate si personalizare', 1);

INSERT INTO FEEDBACKURI
VALUES (SEQ_FEEDBACKURI.NEXTVAL, 7, 'Ok', 4);

INSERT INTO FEEDBACKURI
VALUES (SEQ_FEEDBACKURI.NEXTVAL, 8, 'Foarte ok, recomand', 7);

INSERT INTO FEEDBACKURI
VALUES (SEQ_FEEDBACKURI.NEXTVAL, 9, 'De incredere', 8);

SELECT *
FROM FEEDBACKURI;


-- 5) Table COLECTII

CREATE TABLE COLECTII (
    ID_COLECTIE NUMBER PRIMARY KEY,
    NUME VARCHAR2(60),
    TEMATICA VARCHAR2(60),
    AN NUMBER CHECK (an > 1999),
    ANOTIMP VARCHAR2(30)
);

INSERT INTO COLECTII (id_colectie, nume, tematica, an, anotimp)
VALUES (SEQ_COLECTII.NEXTVAL, 'Prima Verra', 'Florala', 2022, 'Primavara');

INSERT INTO COLECTII
VALUES (SEQ_COLECTII.NEXTVAL, 'Summertime', 'Diafana', 2023, 'Vara');

INSERT INTO COLECTII (id_colectie, nume, an, anotimp)
VALUES (SEQ_COLECTII.NEXTVAL, 'Cozy', 2020, 'Iarna');

INSERT INTO COLECTII
VALUES (SEQ_COLECTII.NEXTVAL, 'Queen Gambit', 'Rosu si negru', 2023, 'Toamna-Iarna');

INSERT INTO COLECTII
VALUES (SEQ_COLECTII.NEXTVAL, 'Sweet Autumn', NULL, 2019, 'Toamna');

INSERT INTO COLECTII
VALUES (SEQ_COLECTII.NEXTVAL, 'Pastel', 'Culori pastelate', 2023, 'Primavara');

INSERT INTO COLECTII
VALUES (SEQ_COLECTII.NEXTVAL, 'Jewels', 'Pietre pretioase', 2020, 'Iarna');

INSERT INTO COLECTII
VALUES (SEQ_COLECTII.NEXTVAL, 'Kaleidoscope', 'Multicolor', 2021, 'Vara');

SELECT *
FROM COLECTII;


-- 6) Table PRODUSE

CREATE TABLE PRODUSE (
    ID_PRODUS NUMBER PRIMARY KEY,
    NUME VARCHAR2(30),
    PRET DECIMAL(10, 2) CHECK (PRET > 0),
    DESCRIERE VARCHAR2(100),
    ID_COMANDA NUMBER,
    ID_COLECTIE NUMBER,
    CONSTRAINT FK_PRODUSE_COMENZI FOREIGN KEY (ID_COMANDA) REFERENCES COMENZI(ID_COMANDA),
    CONSTRAINT fk_PRODUSE_COLECTII FOREIGN KEY (ID_COLECTIE) REFERENCES COLECTII(ID_COLECTIE)
);

INSERT INTO PRODUSE (ID_PRODUS, NUME, PRET, DESCRIERE, ID_COMANDA, ID_COLECTIE)
VALUES (SEQ_PRODUSE.NEXTVAL, 'Bluza Valurile Marii', 700.00, 'Bluza albastra cu valuri', NULL, 1);

INSERT INTO PRODUSE
VALUES (SEQ_PRODUSE.NEXTVAL, 'Bluza Agata', 600.00, NULL, 2, 7);

INSERT INTO PRODUSE
VALUES (SEQ_PRODUSE.NEXTVAL, 'Cercei Monstera', 30.00, 'Cercei in forma de frunze de monstera', NULL, 5);

INSERT INTO PRODUSE
VALUES (SEQ_PRODUSE.NEXTVAL, 'Cercei Mac', 30.00, 'Cercei in forma de flori de mac', 4, 2);

INSERT INTO PRODUSE
VALUES (SEQ_PRODUSE.NEXTVAL, 'Rochia Breeze', 2000.00, 'Bluza lunga ajurata', 6, 6);

INSERT INTO PRODUSE
VALUES (SEQ_PRODUSE.NEXTVAL, 'Fusta Maxima', 400.00, 'Fusta cloche in degrade', 1, 7);

INSERT INTO PRODUSE
VALUES (SEQ_PRODUSE.NEXTVAL, 'Cardiganul Kilipirro', 800.00, 'Cardigan cu nasturi scurt', 2, NULL);

INSERT INTO PRODUSE
VALUES (SEQ_PRODUSE.NEXTVAL, 'Cardiganul Smarald', 900.00, 'Cardigan pana in talie verde', NULL, 7);

INSERT INTO PRODUSE
VALUES (SEQ_PRODUSE.NEXTVAL, 'Cercei Picatura', 30.00, 'Cercei in forma de picatura de ploaie', NULL, NULL);

INSERT INTO PRODUSE
VALUES (SEQ_PRODUSE.NEXTVAL, 'Puloverul Benovelle', 1200.00, 'Pulover de casmir cu guler pe gat', 4, NULL);

SELECT *
FROM PRODUSE;


-- 7) Table ANGAJATI

CREATE TABLE ANGAJATI (
    ID_ANGAJAT NUMBER PRIMARY KEY,
    NUME VARCHAR2(30),
    PRENUME VARCHAR2(30),
    TIP VARCHAR2(30),
    EMAIL VARCHAR2(40),
    NR_TEL VARCHAR2(15),
    SALARIU INT CHECK (SALARIU > 0),
    COMISION DECIMAL(10, 2) CHECK (COMISION >= 0 AND COMISION <=100),
    DATA_ANGAJARE DATE
);

INSERT INTO ANGAJATI (ID_ANGAJAT, NUME, PRENUME, TIP, EMAIL, NR_TEL, SALARIU, COMISION, DATA_ANGAJARE)
VALUES (SEQ_ANGAJATI.NEXTVAL, 'Nedelcu', 'Daniel', 'fondator', 'daniel.nedelcu@nidle.com', '+40712345678', 6000, 50.00, TO_DATE('2020-01-01', 'YYYY-MM-DD'));

INSERT INTO ANGAJATI
VALUES (SEQ_ANGAJATI.NEXTVAL, 'Ionescu', 'Diana', 'fondator', 'diana.ionescu@nidle.com', '+40722345678', 6000, 50.00, TO_DATE('2020-01-01', 'YYYY-MM-DD'));

INSERT INTO ANGAJATI
VALUES (SEQ_ANGAJATI.NEXTVAL, 'Georgescu', 'Ana', 'angajat', 'ana.georgescu@nidle.com', '+40732345678', 4000, 15.00, TO_DATE('2021-03-01', 'YYYY-MM-DD'));

INSERT INTO ANGAJATI
VALUES (SEQ_ANGAJATI.NEXTVAL, 'Dumitrescu', 'Vasile', 'angajat', 'vasile.dumitrescu@nidle.com', '+40742345678', 3500, 25.00, TO_DATE('2022-04-01', 'YYYY-MM-DD'));

INSERT INTO ANGAJATI
VALUES (SEQ_ANGAJATI.NEXTVAL, 'Mihai', 'Elena', 'colaborator', 'elena.mihai@nidle.com', '+40752345678', 3000, 75.00, TO_DATE('2024-01-01', 'YYYY-MM-DD'));

INSERT INTO ANGAJATI
VALUES (SEQ_ANGAJATI.NEXTVAL, 'Petrescu', 'George', 'angajat', 'george.petrescu@nidle.com', '+40762345678', 3200, 60.00, TO_DATE('2024-01-01', 'YYYY-MM-DD'));

INSERT INTO ANGAJATI
VALUES (SEQ_ANGAJATI.NEXTVAL, 'Popa', 'Gabriela', 'analizator', 'gabriela.popa@nidle.com', '+40772345678', 4500, 0.00, TO_DATE('2023-07-01', 'YYYY-MM-DD'));

INSERT INTO ANGAJATI
VALUES (SEQ_ANGAJATI.NEXTVAL, 'Stoica', 'Marius', 'colaborator', 'marius.stoica@nidle.com', '+40782345678', 4800, 5.00, TO_DATE('2023-08-01', 'YYYY-MM-DD'));

INSERT INTO ANGAJATI
VALUES (SEQ_ANGAJATI.NEXTVAL, 'Tudor', 'Irina', 'angajat', 'irina.tudor@nidle.com', '+40792345678', 3700, 80.00, TO_DATE('2023-09-01', 'YYYY-MM-DD'));

INSERT INTO ANGAJATI
VALUES (SEQ_ANGAJATI.NEXTVAL, 'Diaconu', 'Adrian', 'angajat', 'adrian.diaconu@nidle.com', '+40702345678', 4200, 90.00, TO_DATE('2023-10-01', 'YYYY-MM-DD'));

SELECT *
FROM ANGAJATI;


-- 8) Table CROITORI

CREATE TABLE CROITORI (
    ID_CROITOR NUMBER,
    ID_ANGAJAT NUMBER,
    PRIMARY KEY (ID_CROITOR, ID_ANGAJAT),
    CONSTRAINT FK_CROITORI_ANGAJATI FOREIGN KEY (ID_ANGAJAT) REFERENCES ANGAJATI(ID_ANGAJAT),
    CONSTRAINT UNIQUE_ID_CROITOR UNIQUE (ID_CROITOR)
);

INSERT INTO CROITORI (ID_CROITOR, ID_ANGAJAT)
VALUES (SEQ_CROITORI.NEXTVAL, 1);

INSERT INTO CROITORI (ID_CROITOR, ID_ANGAJAT)
VALUES (SEQ_CROITORI.NEXTVAL, 3);

INSERT INTO CROITORI (ID_CROITOR, ID_ANGAJAT)
VALUES (SEQ_CROITORI.NEXTVAL, 4);

INSERT INTO CROITORI (ID_CROITOR, ID_ANGAJAT)
VALUES (SEQ_CROITORI.NEXTVAL, 5);

INSERT INTO CROITORI (ID_CROITOR, ID_ANGAJAT)
VALUES (SEQ_CROITORI.NEXTVAL, 9);

INSERT INTO CROITORI (ID_CROITOR, ID_ANGAJAT)
VALUES (SEQ_CROITORI.NEXTVAL, 10);

INSERT INTO CROITORI (ID_CROITOR, ID_ANGAJAT)
VALUES (SEQ_CROITORI.NEXTVAL, 6);

INSERT INTO CROITORI (ID_CROITOR, ID_ANGAJAT)
VALUES (SEQ_CROITORI.NEXTVAL, 8);

SELECT *
FROM CROITORI;


-- 9) Table DESIGNERI

CREATE TABLE DESIGNERI (
    ID_DESIGNER NUMBER,
    ID_ANGAJAT NUMBER,
    PRIMARY KEY (ID_DESIGNER, ID_ANGAJAT),
    CONSTRAINT FK_DESIGNERI_ANGAJATI FOREIGN KEY (ID_ANGAJAT) REFERENCES ANGAJATI(ID_ANGAJAT),
    CONSTRAINT UNIQUE_ID_DESIGNER UNIQUE (ID_DESIGNER)
);

INSERT INTO DESIGNERI (ID_DESIGNER, ID_ANGAJAT)
VALUES (SEQ_DESIGNERI.NEXTVAL, 1);

INSERT INTO DESIGNERI (ID_DESIGNER, ID_ANGAJAT)
VALUES (SEQ_DESIGNERI.NEXTVAL, 2);

INSERT INTO DESIGNERI (ID_DESIGNER, ID_ANGAJAT)
VALUES (SEQ_DESIGNERI.NEXTVAL, 7);

INSERT INTO DESIGNERI (ID_DESIGNER, ID_ANGAJAT)
VALUES (SEQ_DESIGNERI.NEXTVAL, 3);

INSERT INTO DESIGNERI (ID_DESIGNER, ID_ANGAJAT)
VALUES (SEQ_DESIGNERI.NEXTVAL, 8);

INSERT INTO DESIGNERI (ID_DESIGNER, ID_ANGAJAT)
VALUES (SEQ_DESIGNERI.NEXTVAL, 4);

SELECT *
FROM DESIGNERI;


-- 10) Table SARCINI (asociativ)

CREATE TABLE SARCINI (
    ID_SARCINA NUMBER PRIMARY KEY,
    DESCRIERE VARCHAR2(100),
    ID_CROITOR NUMBER,
    ID_DESIGNER NUMBER,
    ID_PRODUS NUMBER,
    CONSTRAINT FK_SARCINI_CROITORI FOREIGN KEY (ID_CROITOR) REFERENCES CROITORI(ID_CROITOR),
    CONSTRAINT FK_SARCINI_DESIGNERI FOREIGN KEY (ID_DESIGNER) REFERENCES DESIGNERI(ID_DESIGNER),
    CONSTRAINT FK_SARCINI_PRODUSE FOREIGN KEY (ID_PRODUS) REFERENCES PRODUSE(ID_PRODUS)
);

INSERT INTO SARCINI (ID_SARCINA, DESCRIERE, ID_CROITOR, ID_DESIGNER, ID_PRODUS)
VALUES (SEQ_SARCINI.NEXTVAL, 'Cusut bluza', 1, 1, 1);

INSERT INTO SARCINI (ID_SARCINA, DESCRIERE, ID_CROITOR, ID_DESIGNER, ID_PRODUS)
VALUES (SEQ_SARCINI.NEXTVAL, 'Cusut fusta', 2, 1, 2);

INSERT INTO SARCINI (ID_SARCINA, DESCRIERE, ID_CROITOR, ID_DESIGNER, ID_PRODUS)
VALUES (SEQ_SARCINI.NEXTVAL, 'Modelat rochie', 3, 4, 5);

INSERT INTO SARCINI (ID_SARCINA, DESCRIERE, ID_CROITOR, ID_DESIGNER, ID_PRODUS)
VALUES (SEQ_SARCINI.NEXTVAL, 'Croire pulover', 4, NULL, 10);

INSERT INTO SARCINI (ID_SARCINA, DESCRIERE, ID_CROITOR, ID_DESIGNER, ID_PRODUS)
VALUES (SEQ_SARCINI.NEXTVAL, 'Realizare cardigan', 5, 2, 7);

INSERT INTO SARCINI (ID_SARCINA, DESCRIERE, ID_CROITOR, ID_DESIGNER, ID_PRODUS)
VALUES (SEQ_SARCINI.NEXTVAL, 'Proiectare rochie', NULL, 1, 6);

INSERT INTO SARCINI (ID_SARCINA, DESCRIERE, ID_CROITOR, ID_DESIGNER, ID_PRODUS)
VALUES (SEQ_SARCINI.NEXTVAL, 'Modelat bluza', 5, 2, 4);

INSERT INTO SARCINI (ID_SARCINA, DESCRIERE, ID_CROITOR, ID_DESIGNER, ID_PRODUS)
VALUES (SEQ_SARCINI.NEXTVAL, 'Croire fusta', NULL, 3, 3);

INSERT INTO SARCINI (ID_SARCINA, DESCRIERE, ID_CROITOR, ID_DESIGNER, ID_PRODUS)
VALUES (SEQ_SARCINI.NEXTVAL, 'Realizare cercei', 8, 4, 9);

INSERT INTO SARCINI (ID_SARCINA, DESCRIERE, ID_CROITOR, ID_DESIGNER, ID_PRODUS)
VALUES (SEQ_SARCINI.NEXTVAL, 'Modelat pulover', NULL, 5, 8);

INSERT INTO SARCINI (ID_SARCINA, DESCRIERE, ID_CROITOR, ID_DESIGNER, ID_PRODUS)
VALUES (SEQ_SARCINI.NEXTVAL, 'Croire bluza', 6, NULL, 2);

INSERT INTO SARCINI (ID_SARCINA, DESCRIERE, ID_CROITOR, ID_DESIGNER, ID_PRODUS)
VALUES (SEQ_SARCINI.NEXTVAL, 'Realizare fusta', 7, 6, 4);

INSERT INTO SARCINI (ID_SARCINA, DESCRIERE, ID_CROITOR, ID_DESIGNER, ID_PRODUS)
VALUES (SEQ_SARCINI.NEXTVAL, 'Asamblat cercei', 8, 2, 1);

INSERT INTO SARCINI (ID_SARCINA, DESCRIERE, ID_CROITOR, ID_DESIGNER, ID_PRODUS)
VALUES (SEQ_SARCINI.NEXTVAL, 'Modelat cardigan', 7, 5, 5);

INSERT INTO SARCINI (ID_SARCINA, DESCRIERE, ID_CROITOR, ID_DESIGNER, ID_PRODUS)
VALUES (SEQ_SARCINI.NEXTVAL, 'Croire pulover', 7, 1, 6);

SELECT *
FROM SARCINI;


-- 11) Table MATERIALE

CREATE TABLE MATERIALE (
    ID_MATERIAL NUMBER PRIMARY KEY,
    NUME VARCHAR2(30),
    TIP VARCHAR2(30),
    COMPOZITIE VARCHAR2(100)
);

INSERT INTO MATERIALE (ID_MATERIAL, NUME, TIP, COMPOZITIE)
VALUES (SEQ_MATERIALE.NEXTVAL, 'Bumbac', 'Material textil', '100% bumbac');

INSERT INTO MATERIALE (ID_MATERIAL, NUME, TIP, COMPOZITIE)
VALUES (SEQ_MATERIALE.NEXTVAL, 'Poliester', 'Material textil', '100% poliester');

INSERT INTO MATERIALE (ID_MATERIAL, NUME, TIP, COMPOZITIE)
VALUES (SEQ_MATERIALE.NEXTVAL, 'Lana', 'Material textil', '100% lana merinos');

INSERT INTO MATERIALE (ID_MATERIAL, NUME, TIP, COMPOZITIE)
VALUES (SEQ_MATERIALE.NEXTVAL, 'Matase', 'Material textil', '100% matase naturala');

INSERT INTO MATERIALE (ID_MATERIAL, NUME, TIP, COMPOZITIE)
VALUES (SEQ_MATERIALE.NEXTVAL, 'Piele', 'Material', 'Piele naturala');

INSERT INTO MATERIALE (ID_MATERIAL, NUME, TIP, COMPOZITIE)
VALUES (SEQ_MATERIALE.NEXTVAL, 'Denim', 'Material textil', '100% bumbac denim');

INSERT INTO MATERIALE (ID_MATERIAL, NUME, TIP, COMPOZITIE)
VALUES (SEQ_MATERIALE.NEXTVAL, 'Nailon', 'Material textil', '100% nailon');

INSERT INTO MATERIALE (ID_MATERIAL, NUME, TIP, COMPOZITIE)
VALUES (SEQ_MATERIALE.NEXTVAL, 'Matase artificiala', 'Material textil', 'Matase artificiala');

INSERT INTO MATERIALE (ID_MATERIAL, NUME, TIP, COMPOZITIE)
VALUES (SEQ_MATERIALE.NEXTVAL, 'Lycra', 'Material textil', '95% poliester, 5% lycra');

INSERT INTO MATERIALE (ID_MATERIAL, NUME, TIP, COMPOZITIE)
VALUES (SEQ_MATERIALE.NEXTVAL, 'Acetat', 'Material textil', '100% acetat');

SELECT *
FROM MATERIALE;


-- 12) Table TIPARE

CREATE TABLE TIPARE (
    ID_TIPAR NUMBER PRIMARY KEY,
    LUNGIME INT,
    LATIME INT,
    ID_DESIGNER NUMBER,
    ID_PRODUS NUMBER,
    ID_MATERIAL NUMBER,
    CONSTRAINT FK_TIPARE_DESIGNERI FOREIGN KEY (ID_DESIGNER) REFERENCES DESIGNERI(ID_DESIGNER),
    CONSTRAINT FK_TIPARE_PRODUSE FOREIGN KEY (ID_PRODUS) REFERENCES PRODUSE(ID_PRODUS),
    CONSTRAINT FK_TIPARE_MATERIALE FOREIGN KEY (ID_MATERIAL) REFERENCES MATERIALE(ID_MATERIAL)
);

INSERT INTO TIPARE (ID_TIPAR, LUNGIME, LATIME, ID_DESIGNER, ID_PRODUS, ID_MATERIAL)
VALUES (SEQ_TIPARE.NEXTVAL, 50, 30, 1, NULL, 1);

INSERT INTO TIPARE (ID_TIPAR, LUNGIME, LATIME, ID_DESIGNER, ID_PRODUS, ID_MATERIAL)
VALUES (SEQ_TIPARE.NEXTVAL, 60, 40, 2, NULL, 2);

INSERT INTO TIPARE (ID_TIPAR, LUNGIME, LATIME, ID_DESIGNER, ID_PRODUS, ID_MATERIAL)
VALUES (SEQ_TIPARE.NEXTVAL, 70, 50, 3, 1, NULL);

INSERT INTO TIPARE (ID_TIPAR, LUNGIME, LATIME, ID_DESIGNER, ID_PRODUS, ID_MATERIAL)
VALUES (SEQ_TIPARE.NEXTVAL, 80, 60, 4, 2, 3);

INSERT INTO TIPARE (ID_TIPAR, LUNGIME, LATIME, ID_DESIGNER, ID_PRODUS, ID_MATERIAL)
VALUES (SEQ_TIPARE.NEXTVAL, 90, 70, NULL, 3, 4);

INSERT INTO TIPARE (ID_TIPAR, LUNGIME, LATIME, ID_DESIGNER, ID_PRODUS, ID_MATERIAL)
VALUES (SEQ_TIPARE.NEXTVAL, 100, 80, NULL, 4, 5);

INSERT INTO TIPARE (ID_TIPAR, LUNGIME, LATIME, ID_DESIGNER, ID_PRODUS, ID_MATERIAL)
VALUES (SEQ_TIPARE.NEXTVAL, 110, 90, 5, NULL, 6);

INSERT INTO TIPARE (ID_TIPAR, LUNGIME, LATIME, ID_DESIGNER, ID_PRODUS, ID_MATERIAL)
VALUES (SEQ_TIPARE.NEXTVAL, 120, 100, 6, 5, 7);

INSERT INTO TIPARE (ID_TIPAR, LUNGIME, LATIME, ID_DESIGNER, ID_PRODUS, ID_MATERIAL)
VALUES (SEQ_TIPARE.NEXTVAL, 130, 110, NULL, 6, 8);

INSERT INTO TIPARE (ID_TIPAR, LUNGIME, LATIME, ID_DESIGNER, ID_PRODUS, ID_MATERIAL)
VALUES (SEQ_TIPARE.NEXTVAL, 140, 120, NULL, 7, 9);

SELECT *
FROM TIPARE;


-- 13) Table FURNIZORI

CREATE TABLE FURNIZORI (
    ID_FURNIZOR NUMBER PRIMARY KEY,
    NUME VARCHAR2(50),
    COD_FISCAL INT CHECK (COD_FISCAL > 0)
);

INSERT INTO FURNIZORI (ID_FURNIZOR, NUME, COD_FISCAL)
VALUES (SEQ_FURNIZORI.NEXTVAL, 'SC Fabrica de textile SRL', 123456789);

INSERT INTO FURNIZORI (ID_FURNIZOR, NUME, COD_FISCAL)
VALUES (SEQ_FURNIZORI.NEXTVAL, 'SC Furnizorul de accesorii SRL', 987654321);

INSERT INTO FURNIZORI (ID_FURNIZOR, NUME, COD_FISCAL)
VALUES (SEQ_FURNIZORI.NEXTVAL, 'SC Distribuitorul de mătase SA', 456789123);

INSERT INTO FURNIZORI (ID_FURNIZOR, NUME, COD_FISCAL)
VALUES (SEQ_FURNIZORI.NEXTVAL, 'PFA Producătorul de piele', 789123456);

INSERT INTO FURNIZORI (ID_FURNIZOR, NUME, COD_FISCAL)
VALUES (SEQ_FURNIZORI.NEXTVAL, 'SC Distribuitorul de dantelă SRL', 321654987);

INSERT INTO FURNIZORI (ID_FURNIZOR, NUME, COD_FISCAL)
VALUES (SEQ_FURNIZORI.NEXTVAL, 'SC Fabrica de mătase SA', 654987321);

INSERT INTO FURNIZORI (ID_FURNIZOR, NUME, COD_FISCAL)
VALUES (SEQ_FURNIZORI.NEXTVAL, 'PFA Producătorul de dungi', 987321654);

INSERT INTO FURNIZORI (ID_FURNIZOR, NUME, COD_FISCAL)
VALUES (SEQ_FURNIZORI.NEXTVAL, 'SC Furnizorul de nasturi SA', 159753468);

INSERT INTO FURNIZORI (ID_FURNIZOR, NUME, COD_FISCAL)
VALUES (SEQ_FURNIZORI.NEXTVAL, 'SC Fabrica de dantelă SRL', 357951468);

INSERT INTO FURNIZORI (ID_FURNIZOR, NUME, COD_FISCAL)
VALUES (SEQ_FURNIZORI.NEXTVAL, 'SC Violette Andrele SA', 468135792);

SELECT *
FROM FURNIZORI;


-- 14) Table CONTRACTE

CREATE TABLE CONTRACTE (
    ID_CONTRACT NUMBER NOT NULL,
    DATA DATE,
    ID_FURNIZOR NUMBER NOT NULL,
    ID_MATERIAL NUMBER NOT NULL,
    PRIMARY KEY (ID_CONTRACT, ID_FURNIZOR, ID_MATERIAL),
    CONSTRAINT FK_CONTRACTE_FURNIZORI FOREIGN KEY (ID_FURNIZOR) REFERENCES FURNIZORI(ID_FURNIZOR),
    CONSTRAINT FK_CONTRACTE_MATERIALE FOREIGN KEY (ID_MATERIAL) REFERENCES MATERIALE(ID_MATERIAL)
);

INSERT INTO CONTRACTE (ID_CONTRACT, DATA, ID_FURNIZOR, ID_MATERIAL) 
VALUES (SEQ_CONTRACTE.NEXTVAL, TO_DATE('2023-01-15', 'YYYY-MM-DD'), 1, 1);

INSERT INTO CONTRACTE (ID_CONTRACT, DATA, ID_FURNIZOR, ID_MATERIAL) 
VALUES (SEQ_CONTRACTE.NEXTVAL, TO_DATE('2023-02-20', 'YYYY-MM-DD'), 2, 2);

INSERT INTO CONTRACTE (ID_CONTRACT, DATA, ID_FURNIZOR, ID_MATERIAL) 
VALUES (SEQ_CONTRACTE.NEXTVAL, TO_DATE('2023-03-10', 'YYYY-MM-DD'), 3, 3);

INSERT INTO CONTRACTE (ID_CONTRACT, DATA, ID_FURNIZOR, ID_MATERIAL) 
VALUES (SEQ_CONTRACTE.NEXTVAL, TO_DATE('2023-04-05', 'YYYY-MM-DD'), 4, 4);

INSERT INTO CONTRACTE (ID_CONTRACT, DATA, ID_FURNIZOR, ID_MATERIAL) 
VALUES (SEQ_CONTRACTE.NEXTVAL, TO_DATE('2023-05-18', 'YYYY-MM-DD'), 5, 5);

INSERT INTO CONTRACTE (ID_CONTRACT, DATA, ID_FURNIZOR, ID_MATERIAL) 
VALUES (SEQ_CONTRACTE.NEXTVAL, TO_DATE('2023-06-22', 'YYYY-MM-DD'), 6, 6);

INSERT INTO CONTRACTE (ID_CONTRACT, DATA, ID_FURNIZOR, ID_MATERIAL) 
VALUES (SEQ_CONTRACTE.NEXTVAL, TO_DATE('2023-07-09', 'YYYY-MM-DD'), 7, 7);

INSERT INTO CONTRACTE (ID_CONTRACT, DATA, ID_FURNIZOR, ID_MATERIAL) 
VALUES (SEQ_CONTRACTE.NEXTVAL, TO_DATE('2023-08-14', 'YYYY-MM-DD'), 8, 8);

INSERT INTO CONTRACTE (ID_CONTRACT, DATA, ID_FURNIZOR, ID_MATERIAL) 
VALUES (SEQ_CONTRACTE.NEXTVAL, TO_DATE('2023-09-30', 'YYYY-MM-DD'), 9, 9);

INSERT INTO CONTRACTE (ID_CONTRACT, DATA, ID_FURNIZOR, ID_MATERIAL) 
VALUES (SEQ_CONTRACTE.NEXTVAL, TO_DATE('2023-10-25', 'YYYY-MM-DD'), 10, 10);

INSERT INTO CONTRACTE (ID_CONTRACT, DATA, ID_FURNIZOR, ID_MATERIAL) 
VALUES (SEQ_CONTRACTE.NEXTVAL, TO_DATE('2023-11-12', 'YYYY-MM-DD'), 1, 6);

INSERT INTO CONTRACTE (ID_CONTRACT, DATA, ID_FURNIZOR, ID_MATERIAL) 
VALUES (SEQ_CONTRACTE.NEXTVAL, TO_DATE('2023-12-03', 'YYYY-MM-DD'), 2, 7);

INSERT INTO CONTRACTE (ID_CONTRACT, DATA, ID_FURNIZOR, ID_MATERIAL) 
VALUES (SEQ_CONTRACTE.NEXTVAL, TO_DATE('2024-01-28', 'YYYY-MM-DD'), 3, 8);

INSERT INTO CONTRACTE (ID_CONTRACT, DATA, ID_FURNIZOR, ID_MATERIAL) 
VALUES (SEQ_CONTRACTE.NEXTVAL, TO_DATE('2024-02-10', 'YYYY-MM-DD'), 4, 9);

INSERT INTO CONTRACTE (ID_CONTRACT, DATA, ID_FURNIZOR, ID_MATERIAL) 
VALUES (SEQ_CONTRACTE.NEXTVAL, TO_DATE('2024-03-20', 'YYYY-MM-DD'), 5, 10);

SELECT *
FROM CONTRACTE;


-- Change for the PRINCE column in ORDERS:

UPDATE COMENZI C
SET C.PRET = (
    SELECT SUM(P.PRET)
    FROM PRODUSE P
    WHERE P.ID_COMANDA = C.ID_COMANDA
    AND P.PRET IS NOT NULL
); 